### ISSUE TITLE
Add slack-access data classification

### ISSUE THREAD

**Issue by jens1o** [mozilla-iam/dino-park-front-end#530]
**Is your feature request related to a problem? Please describe.**
Checking whether a contributor has access to the Slack instance is always complicated, as you need to scroll to the very bottom and then check whether the user has the `slack-access` access group.

**Describe the solution you'd like**
Like with the current markers, I'd imagine something next to it that appears as soon as this user has access to Slack.

See this:
![image showing a Slack badge next to the `Mozilla-Confidential` badge](https://user-images.githubusercontent.com/11234139/69601103-6bf71780-1013-11ea-8010-63dda06a5d72.png)

**Describe alternatives you've considered**
Maybe this could be expanded to a popover of the user in other contexts as well.

ref #508 

---

If wanted, this seems like a thing I could contribute myself. :)

**Comment by LeoMcA** [comment]
> If wanted, this seems like a thing I could contribute myself. :)

That would be amazing!

So, as I originally envisaged this, the "access to" section would just contain the one label, but I was looking at this from the view of staff accounts (which have limited space in that area because of additional fields in that area):

![Screenshot from 2019-11-27 12-38-40](https://user-images.githubusercontent.com/755354/69724079-012d0580-1113-11ea-9c8e-c3b2cdec6e41.png)

(For instance, you'll see that only "staff only" is listed in my profile, not "mozilla confidential" and "public" which I'm also necessarily in because of that classification).

Internally there was a little bit of discussion of expanding that beyond what data classification a person had access to, to what tools that actually granted them access to. I had though that this section would have to be somewhere else - either a pop-over, or another section in the main body - because of the space constraints on the staff profile.

There's loads more space on the contributor profile, so I think the suggestion in your screenshot is a great first step. Please feel free to work on it! @fiji-flo tells me you already have a development environment set up, if you need any further help with that (or have any questions about anything) please reach out to either of us.

**Comment by jens1o** [comment]
Thanks for the helpful comment! I'll look into it after Wednesday (then I'm done with all exams this year). :)
